### ISSUE TITLE
About the relevance score

### ISSUE THREAD

**Issue by w-y-li** [sunnweiwei/RankGPT#10]
Hi I wander how you deal with the relevance score?Do you only see the score 2 as relevant passage or also see score 1 as relevant passage?What do you think the passage with score 1 as,relevant,or irrelevant?

**Comment by sunnweiwei** [comment]
Hi The evaluation implementation can be referred to [pytrec_eval](https://github.com/cvangysel/pytrec_eval). For the `Recall` metric, all non-zero passages are considered relevant. For the `nDCG` metric, graded relevance scores are used to calculate [nDCG](https://en.wikipedia.org/wiki/Discounted_cumulative_gain).

**Comment by w-y-li** [comment]
Thanks for your answer.And I also want to know that how exactly dou you deal with the trec-covid dataset in BEIR,this dataset has too many postive passages,do you rank them directly or first sample some relevant passages then do the ranking task.

**Comment by sunnweiwei** [comment]
I retrieved 100 passages from the entire passage collection using BM25 (https://github.com/castorini/pyserini), and then re-ranked these top-100 passages using GPT.
