### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by Yelrose** [sunnweiwei/RankGPT#11]
https://github.com/sunnweiwei/RankGPT/blob/b080727b6cb660b51f4158f1e893eb8bc732063d/run_evaluation.py#L89C24-L89C24

```
new_item = sliding_windows(item, rank_start=0, rank_end=10, window_size=20, step=10,
                                   model_name='gpt-3.5-turbo', api_key=openai_key)
```

The rank_end is less then window_size.

**Comment by sunnweiwei** [comment]
Yes, this is a typo; I have fixed it. Thanks!
