### ISSUE TITLE
can RankGPT be fine tuning to specific filed？

### ISSUE THREAD

**Issue by VictoryBlue** [sunnweiwei/RankGPT#12]

**Comment by sunnweiwei** [comment]
I have not tried fine-tuning, but I would recommend following OpenAI's [guidebook](https://platform.openai.com/docs/guides/fine-tuning/when-to-use-fine-tuning) and considering fine-tuning only if prompting is not yielding satisfactory results and high-quality data is available. Besides, if you are considering fine-tuning an open-source model, you may refer to [Permutation Distillation](https://github.com/sunnweiwei/RankGPT#training-specialized-models) and [Instruction Distillation](https://github.com/sunnweiwei/RankGPT/tree/main/InstructDistill).
