### ISSUE TITLE
About predicted relevance score in NDCG

### ISSUE THREAD

**Issue by zlh-source** [sunnweiwei/RankGPT#13]
Hello, the listwise method can generate the relevance order of candidate documents instead of the relevance score. When you calculate ndcg, how do you input your predicted relevance score into the ndcg function?

I looked at your [code](https://github.com/sunnweiwei/RankGPT/blob/b400cb29e3befa6b6a3e01482b290e3885a85d6a/trec_eval.py#L67C43-L67C43) and it seems that if the k-th relevant document is ranked, then its predicted relevance score is 1/k ?

**Comment by sunnweiwei** [comment]
Hi. The calculation of NDCG doesn't utilize predicted relevance scores. The code you mentioned is adapted from https://github.com/castorini/pyserini/blob/master/pyserini/eval/trec_eval.py.
