### ISSUE TITLE
ImportError: cannot import name 'OpenAI' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)

### ISSUE THREAD

**Issue by VictoryBlue** [sunnweiwei/RankGPT#20]
[/content/RankGPT/rank_gpt.py](https://localhost:8080/#) in __init__(self, keys, start_id, proxy)
      7 class OpenaiClient:
      8     def __init__(self, keys=None, start_id=None, proxy=None):
----> 9         from openai import OpenAI
     10         import openai
     11         if isinstance(keys, str):

ImportError: cannot import name 'OpenAI' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)

**Comment by sunnweiwei** [comment]
You could try upgrading openai: `pip install -U openai`
