### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bclavie** [sunnweiwei/RankGPT#22]
Hey @sunnweiwei, I see that the repo doesn't have a license. I'm interested in integrating it (alongside other reranking methods) to make using more straightforward.

edit: I saw you added the Apache license badge on the README.md, thank you very much, I'll integrate it!
However, would you mind also adding a LICENSE file to the repo? This'd be very helpful to meet automated checks!

**Comment by sunnweiwei** [comment]
Hi, Thanks for your interest in integrating  our repo! I have uploaded the license file.
