### ISSUE TITLE
How to evaluate on NovelEval?

### ISSUE THREAD

**Issue by XingshuaiZhang** [sunnweiwei/RankGPT#25]
Hi, nice work! Congratulations on the Outstanding Paper award!

I am a beginner in the field of information retrieval. During the process of reading the code, I found that RankGPT only provided evaluation code for the TREC, BEIR, and Mr.TyDi datasets, and did not provide evaluation code for the NovelEval dataset. How should I evaluate on the NovelEval dataset? May I ask if this part of the code will be released? Thank you!

**Comment by Albert-Ma** [comment]
@sunnweiwei

**Comment by XingshuaiZhang** [comment]
Thank you, I have solved the problem.

**Comment by 1204120** [comment]
> Thank you, I have solved the problem.谢谢你，我已经解决了问题。

Hello, I would like to ask how to evaluate it, thank you~
