### ISSUE TITLE
Understand the sliding window method

### ISSUE THREAD

**Issue by ZeratuuLL** [sunnweiwei/RankGPT#26]
I find I don't quite understand the sliding windown method in the paper and I will use a slightly different example from what's in the paper (Figure 3) to illustrate my question. I will first give my understand of what the paper writes and then ask the question. Please help to understand my confusion or let me know if my understand is wrong!

In the paper, when there are 8 passages, the algorithm first rank (5, 6, 7, 8) and get reranking result (8, 5, 6, 7)
Then the window moves left to compares (3, 4, 8, 5) and get reranking result (8, 3, 4, 5).

Here is understandable that we already have 3 > 4 > 5 and 5 > 6 > 7 so there is no need to further compare 3, 4 vs 6, 7. However, what if the reranking result of (3 ,4 ,8, 5) is (8, 5, 3, 4)? In this case should we compare 3, 4 vs 5, 6? When reading the [code](https://github.com/sunnweiwei/RankGPT/blob/main/rank_gpt.py#L234) I don't see any considerations for this. So would like to know if my understanding is wrong, or some other assumptions are made here! Thank you very much for the explanation!

**Comment by sunnweiwei** [comment]
Hi! Your understanding is correct. The sliding window can only guarantee that the top-ranked document is fully compared. This is acceptable if we only care about the top-ranked documents, e.g., the top 10. To further refine the entire list, we could run multiple sliding windows, similar to how bubble sort works.

**Comment by ZeratuuLL** [comment]
Thanks for the reply! The explanation makes sense! Thank you!
