### ISSUE TITLE
initializing rank_start correct?

### ISSUE THREAD

**Issue by DRRV** [sunnweiwei/RankGPT#3]
I am wondering whether line [228](https://github.com/sunnweiwei/RankGPT/blob/0dd95678d52b77c5d04e3644f6462e271af909ce/rank_gpt.py#L228)  end_pos = rank_start is correct?  is it not rather end_pos  == rank_end

**Comment by sunnweiwei** [comment]
Thank you for pointing this issue! It should be `end_pos = rank_end`.
I fixed this in https://github.com/sunnweiwei/RankGPT/commit/d0f338802b0091a9ff4745b9af29051962b960b5.
