### ISSUE TITLE
Title in dataset

### ISSUE THREAD

**Issue by ronakice** [sunnweiwei/RankGPT#4]
I was going through the dataset you used to train the distilled modesl, and noticed a title. 

`{"query": "how was google founded", "query_id": "387441", "positive_passages": [{"docid": "5210298", "title": "What year was Google founded?", "text": "Google was co-founded in by Larry Page and Sergey Brin while they were students at Stanford University. Google was first incorporated as a privately held company on September \u00e2\u0080\u00a64th, 1998. The company name Google has its origin in the word Googol, which is the term for the number that represents 'one followed by hundred zeros'."}], "negative_passages": [{"docid": "7379456", "rank": 1, "text": "Instructions to install the Google Play Services in our Xamarin Android Player or the GenyMotion Emulator can be found here: https://university.xamarin.com/resources/how-to-install-google-play-on-android-emulator.Yes I found this article helpful. No I did not find this article helpful.nstructions to install the Google Play Services in our Xamarin Android Player or the GenyMotion Emulator can be found here: https://university.xamarin.com/resources/how-to-install-google-play-on-android-emulator. Yes I found this article helpful."}, `

MS MARCO Passage Ranking task in the v1 iteration which most if not everyone uses should not have a title from what I can tell. Can you elaborate on why this is here? Thanks :)

**Comment by sunnweiwei** [comment]
The dataset is based on `msmarco-passage` shared by https://huggingface.co/datasets/Tevatron/msmarco-passage. In experiments I only used the `text` field:
https://github.com/sunnweiwei/RankGPT/blob/d0f338802b0091a9ff4745b9af29051962b960b5/specialization.py#L37.

**Comment by ronakice** [comment]
Okay, great thanks for the heads up :) This paper is also relevant to this choice -  https://arxiv.org/pdf/2304.12904.pdf in case you are interested, Tevatron introduced some inconsistencies in the aspect. But I believe your approach carries forward in the intended way!
