### ISSUE TITLE
Unable to replicate the result

### ISSUE THREAD

**Issue by nkn002** [sunnweiwei/RankGPT#9]
Hi,

I was trying to replicate your result on TREC-DL19, particularly by using gpt-3.5-turbo to rerank the top-100 passages retrieved by BM25 on Google Colab. Here is what I got:

ndcg_cut_1            	all	0.7713
ndcg_cut_5            	all	0.7174
ndcg_cut_10           all	0.6805

I simply copied your code on "Example of evaluation on TREC-DL19", and used my openai_key. I cross checked the hyper-parameters of sliding window and they were consistent with those in your paper (w = 20, s = 10, and K = 1). Do you know why this might happen?

Thank you for your time.

**Comment by sunnweiwei** [comment]
Yes, I have also obtained the results you listed when using gpt-3.5-turbo recently. I suspect this may be due to an update in OpenAI's API. If you want to reproduce the results of the paper, you can try using gpt-3.5-turbo-0301.

**Comment by nkn002** [comment]
Thank you for your prompt reply! 

I also suspect that OpenAI updated their gpt3.5 model, but nevertheless I wanted to cross-check it with you. I tried gpt-3.5-turbo-0301 and gpt-3.5-turbo-0613 (OpenAI's recommended replacement for 0301). Here are the results:

0301:
ndcg_cut_1            	all	0.7829
ndcg_cut_5            	all	0.6882
ndcg_cut_10           all	0.6588

0613:
ndcg_cut_1            	all	0.7984
ndcg_cut_5            	all	0.7317
ndcg_cut_10           all	0.6908

Seems like the version that you guys used might have been different.
